<?php
/**
 * Auto generated by prado-cli.php on 2012-08-14 02:31:57.
 */
class ChapterRecord extends TActiveRecord
{
	const TABLE='chapters';

	public $chapter_id;
	public $subject;
	public $title;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>