<?php
/**
 * Auto generated by prado-cli.php on 2012-08-13 09:46:17.
 */
class PostRecord extends TActiveRecord
{
	const TABLE='posts';

	public $post_id;
	public $author_id;
	public $create_time;
	public $title;
	public $content;
	public $status;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
	
	public $author; //holds an UserRecord
 
    public static $RELATIONS=array
    (
        'author' => array(self::BELONGS_TO, 'UserRecord'),
    );
}
?>