<?php
/**
 * Auto generated by prado-cli.php on 2012-08-14 09:08:20.
 */
class ProblemRecord extends TActiveRecord
{
	const TABLE='problems';

	public $problem_id;
	public $chapter_id;
	public $problem_type;
	public $content;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
	
	public static function mathText($chapter_id)
	{
		
		$rec = new ProblemRecord;
		$rec->chapter_id = $chapter_id;
		$rec->problem_type = 'text';
		return $rec;
	}

	public static function mathEquation($chapter_id)
	{
		$rec = new ProblemRecord;
		$rec->chapter_id = $chapter_id;
		$rec->problem_type = 'equation';
		return $rec;
	}
}
?>