<?php
/**
 * Auto generated by prado-cli.php on 2012-08-14 02:31:40.
 */
class SubjectRecord extends TActiveRecord
{
	const TABLE='subjects';

	public $name;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>