<?php
/**
 * Auto generated by prado-cli.php on 2012-08-09 05:14:03.
 */
class UserRecord extends TActiveRecord
{
	const TABLE='users';

	public $username;
	public $email;
	public $password;
	public $role;
	public $first_name;
	public $last_name;

	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
	
	public $posts=array(); //holds an array of PostRecord
 
    public static $RELATIONS=array
    (
        'posts' => array(self::HAS_MANY, 'PostRecord'),
    );
}
?>